# Generated by Django 3.0.8 on 2020-10-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='first', max_length=200),
            preserve_default=False,
        ),
    ]
