# Generated by Django 3.0.8 on 2020-10-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201005_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bno',
            new_name='sno',
        ),
    ]
