# Generated by Django 3.0.5 on 2020-10-07 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201006_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timeStamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
