# Generated by Django 3.0.5 on 2020-10-08 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201008_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timeStamp',
            field=models.DateTimeField(verbose_name=datetime.time(5, 31, 55, 805254)),
        ),
    ]
