# Generated by Django 3.0.5 on 2020-10-08 00:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20201008_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='timeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
