# Generated by Django 3.0.8 on 2020-10-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_overall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='overall',
        ),
    ]
